version: 0.2
env:
  variables:
    IMAGE_REPO_URL: "809695185788.dkr.ecr.ap-southeast-2.amazonaws.com/"
    IMAGE_PLATFORM_NAME: node:16.15.1
    IMAGE_APP_NAME: "api-poc-miraen"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password | docker login --username AWS --password-stdin $IMAGE_REPO_URL
  build:
    commands:
      - echo ========================================
      - echo BUILD STARTED ON `date`
      - echo Building the Docker image...
      - export IMAGE_VERSION=$(date +%Y%m%d%H%M%S)
      - docker build -t $IMAGE_REPO_URL$IMAGE_APP_NAME:$IMAGE_VERSION .
  post_build:
    commands:
      - echo ========================================
      - echo BUILD COMPLETED ON `date`
      - echo Pushing the Docker images...
      - docker push $IMAGE_REPO_URL$IMAGE_APP_NAME:$IMAGE_VERSION
      - echo Writing image definitions file...

      - printf '[{"name":"%s:%s","imageUri":"%s"}]' $IMAGE_APP_NAME $IMAGE_VERSION $IMAGE_REPO_NAME:$IMAGE_VERSION > imagedefinitions.json
cache:
  paths:
    - './node_modules/**/*'
artifacts:
  files:
    #- './**/*'
    - 'appspec.yml'
    - 'stop_server.sh'
    - 'start_server.sh'
