version: 0.2
env:
  variables:
    IMAGE_REPO_URL: $IMAGE_REPO_URL
    IMAGE_PLATFORM_NAME: node:16.15.1
    IMAGE_APP_NAME: $IMAGE_APP_NAME
    IMAGE_VERSION: $IMAGE_VERSION
    PROFILE: $PROFILE
    PROJ_NAME: $PROJ_NAME
    COMPANY_NAME: $COMPANY_NAME
    AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo $IMAGE_REPO_URL
      - aws ecr get-login-password | docker login --username AWS --password-stdin $IMAGE_REPO_URL
      - cp appspec.yml ./appspec.yml
      - cp start_server.sh ./start_server.sh
      - cp stop_server.sh ./stop_server.sh
      - sed -i 's/@PROJ_NAME@/'${PROJ_NAME}'/' ./appspec.yml
      - sed -i 's/@PROFILE@/'${PROFILE}'/; s/@PROJ_NAME@/'${PROJ_NAME}'/; s/@IMAGE_VERSION@/'${IMAGE_VERSION}'/; s/@AWS_ACCOUNT_ID@/'${AWS_ACCOUNT_ID}'/; s/@AWS_DEFAULT_REGION@/'${AWS_DEFAULT_REGION}'/; s/@COMPANY_NAME@/'${COMPANY_NAME}'/;' ./start_server.sh
      - sed -i 's/@PROFILE@/'${PROFILE}'/; s/@PROJ_NAME@/'${PROJ_NAME}'/; s/@IMAGE_VERSION@/'${IMAGE_VERSION}'/; s/@AWS_ACCOUNT_ID@/'${AWS_ACCOUNT_ID}'/; s/@AWS_DEFAULT_REGION@/'${AWS_DEFAULT_REGION}'/; s/@COMPANY_NAME@/'${COMPANY_NAME}'/; s/@AWS_ACCESS_KEY_ID@/'${AWS_ACCESS_KEY_ID}'/; s/@AWS_SECRET_ACCESS_KEY@/'${AWS_SECRET_ACCESS_KEY}'/;' ./stop_server.sh
  build:
    commands:
      - echo ========================================
      - echo BUILD STARTED ON `date`
      - echo Building the Docker image...
      - export IMAGE_VERSION=$(date +%Y%m%d%H%M%S)
      - docker build -t $IMAGE_REPO_URL$IMAGE_APP_NAME:$IMAGE_VERSION .
  post_build:
    commands:
      - echo ========================================
      - echo BUILD COMPLETED ON `date`
      - echo Pushing the Docker images...
      - docker push $IMAGE_REPO_URL$IMAGE_APP_NAME:$IMAGE_VERSION
      - echo Writing image definitions file...
      - printf '[{"name":"%s:%s","imageUri":"%s"}]' $IMAGE_APP_NAME $IMAGE_VERSION $IMAGE_REPO_NAME:$IMAGE_VERSION > imagedefinitions.json
cache:
  paths:
    - './node_modules/**/*'
artifacts:
  files:
    - 'imagedefinitions.json'
    - 'appspec.yml'
    - '.env'
    - 'api_down.sh'
    - 'api_deploy.sh'
    - 'docker-compose.yml'
    - 'redis.conf'
    - 'yarn.lock'
