version: 0.2
env:
  variables:
    IMAGE_REPO_URL: "809695185788.dkr.ecr.ap-southeast-2.amazonaws.com/"
    IMAGE_PLATFORM_NAME: node:18.12.0
    IMAGE_APP_NAME: "brickmate-commerce-backend-dev"
    IMAGE_VERSION: 1.0.0-dev
phases:
  pre_build:
    commands:
      commands:
        - echo Logging in to Amazon ECR...
        - aws ecr get-login-password | docker login --username AWS --password-stdin $IMAGE_REPO_URL
        #- docker pull $IMAGE_REPO_URL$IMAGE_PLATFORM_NAME
        - docker pull node:18.12.0
  build:
    commands:
      - echo ========================================
      - echo BUILD STARTED ON `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_URL$IMAGE_APP_NAME:$IMAGE_VERSION --target production .
  post_build:
    commands:
      - echo ========================================
      - echo BUILD COMPLETED ON `date`
      - echo Pushing the Docker images...
      - docker push $IMAGE_REPO_URL$IMAGE_APP_NAME:$IMAGE_VERSION
      - echo Writing image definitions file...
      - printf '[{"name":"%s:%s","imageUri":"%s"}]' $IMAGE_APP_NAME $IMAGE_VERSION $IMAGE_REPO_NAME:$IMAGE_VERSION > imagedefinitions.json
cache:
  paths:
    - './node_modules/**/*'
artifacts:
  files:
    - 'imagedefinitions.json'
    - 'appspec.yml'
    - '.env'
    - 'api_down.sh'
    - 'api_deploy.sh'
    - 'docker-compose.yml'
    - 'redis.conf'
    - 'yarn.lock'
