#!/bin/sh
PROFILE=@PROFILE@
IMAGE_VERSION=@IMAGE_VERSION@
IMAGE_REPO_URL=@IMAGE_REPO_URL@
IMAGE_APP_NAME=@IMAGE_APP_NAME@
AWS_DEFAULT_REGION=@AWS_DEFAULT_REGION@
I_PORT=3000


if [ "$PROFILE" = "dev" ]; then
    I_PORT=3000
elif [ "$PROFILE" = "prd" ]; then
    I_PORT=3000
fi

echo ${IMAGE_REPO_URL}/${IMAGE_APP_NAME}:$IMAGE_VERSION
sudo docker run \
-d \
-p${I_PORT}:3000 \
--name ${IMAGE_APP_NAME} \
${IMAGE_REPO_URL}/${IMAGE_APP_NAME}:$IMAGE_VERSION \
