version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/@PROJ_NAME@
    overwrite: yes

permissions:
  - object: /home/ec2-user/@PROJ_NAME@
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  AfterInstall:
    - location: /stop_server.sh
      timeout: 180
      runas: ec2-user
ApplicationStart:
  - location: /start_server.sh
    timeout: 180
    runas: ec2-user
